<?php

namespace Hello\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{

    /**
     * @param $title 书的名称
     * @return array
     */
    public function getAllVaildBookByTitle($title){
        return $this->findBy(array('title'=>$title));
    }
}
